/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProprietesRouteImport } from './routes/proprietes'
import { Route as SauvegardesRouteImport } from './routes/sauvegardes'
import { Route as ParametresIndexRouteImport } from './routes/parametres/index'
import { Route as ParametresCarteRouteImport } from './routes/parametres/carte'
import { Route as ParametresCompteRouteImport } from './routes/parametres/compte'
import { Route as ParametresInterfaceRouteImport } from './routes/parametres/interface'
import { Route as ParametresProprietesRouteImport } from './routes/parametres/proprietes'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietesRoute = ProprietesRouteImport.update({
  id: '/proprietes',
  path: '/proprietes',
  getParentRoute: () => rootRouteImport,
} as any)
const SauvegardesRoute = SauvegardesRouteImport.update({
  id: '/sauvegardes',
  path: '/sauvegardes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresIndexRoute = ParametresIndexRouteImport.update({
  id: '/parametres/',
  path: '/parametres/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresCarteRoute = ParametresCarteRouteImport.update({
  id: '/parametres/carte',
  path: '/parametres/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresCompteRoute = ParametresCompteRouteImport.update({
  id: '/parametres/compte',
  path: '/parametres/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresInterfaceRoute = ParametresInterfaceRouteImport.update({
  id: '/parametres/interface',
  path: '/parametres/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresProprietesRoute = ParametresProprietesRouteImport.update({
  id: '/parametres/proprietes',
  path: '/parametres/proprietes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proprietes': typeof ProprietesRoute
  '/sauvegardes': typeof SauvegardesRoute
  '/parametres/carte': typeof ParametresCarteRoute
  '/parametres/compte': typeof ParametresCompteRoute
  '/parametres/interface': typeof ParametresInterfaceRoute
  '/parametres/proprietes': typeof ParametresProprietesRoute
  '/parametres/': typeof ParametresIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proprietes': typeof ProprietesRoute
  '/sauvegardes': typeof SauvegardesRoute
  '/parametres/carte': typeof ParametresCarteRoute
  '/parametres/compte': typeof ParametresCompteRoute
  '/parametres/interface': typeof ParametresInterfaceRoute
  '/parametres/proprietes': typeof ParametresProprietesRoute
  '/parametres': typeof ParametresIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proprietes': typeof ProprietesRoute
  '/sauvegardes': typeof SauvegardesRoute
  '/parametres/carte': typeof ParametresCarteRoute
  '/parametres/compte': typeof ParametresCompteRoute
  '/parametres/interface': typeof ParametresInterfaceRoute
  '/parametres/proprietes': typeof ParametresProprietesRoute
  '/parametres/': typeof ParametresIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/proprietes'
    | '/sauvegardes'
    | '/parametres/carte'
    | '/parametres/compte'
    | '/parametres/interface'
    | '/parametres/proprietes'
    | '/parametres/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/proprietes'
    | '/sauvegardes'
    | '/parametres/carte'
    | '/parametres/compte'
    | '/parametres/interface'
    | '/parametres/proprietes'
    | '/parametres'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/proprietes'
    | '/sauvegardes'
    | '/parametres/carte'
    | '/parametres/compte'
    | '/parametres/interface'
    | '/parametres/proprietes'
    | '/parametres/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProprietesRoute: typeof ProprietesRoute
  SauvegardesRoute: typeof SauvegardesRoute
  ParametresCarteRoute: typeof ParametresCarteRoute
  ParametresCompteRoute: typeof ParametresCompteRoute
  ParametresInterfaceRoute: typeof ParametresInterfaceRoute
  ParametresProprietesRoute: typeof ParametresProprietesRoute
  ParametresIndexRoute: typeof ParametresIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietes': {
      id: '/proprietes'
      path: '/proprietes'
      fullPath: '/proprietes'
      preLoaderRoute: typeof ProprietesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauvegardes': {
      id: '/sauvegardes'
      path: '/sauvegardes'
      fullPath: '/sauvegardes'
      preLoaderRoute: typeof SauvegardesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/': {
      id: '/parametres/'
      path: '/parametres'
      fullPath: '/parametres/'
      preLoaderRoute: typeof ParametresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/carte': {
      id: '/parametres/carte'
      path: '/parametres/carte'
      fullPath: '/parametres/carte'
      preLoaderRoute: typeof ParametresCarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/compte': {
      id: '/parametres/compte'
      path: '/parametres/compte'
      fullPath: '/parametres/compte'
      preLoaderRoute: typeof ParametresCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/interface': {
      id: '/parametres/interface'
      path: '/parametres/interface'
      fullPath: '/parametres/interface'
      preLoaderRoute: typeof ParametresInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/proprietes': {
      id: '/parametres/proprietes'
      path: '/parametres/proprietes'
      fullPath: '/parametres/proprietes'
      preLoaderRoute: typeof ParametresProprietesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProprietesRoute: ProprietesRoute,
  SauvegardesRoute: SauvegardesRoute,
  ParametresCarteRoute: ParametresCarteRoute,
  ParametresCompteRoute: ParametresCompteRoute,
  ParametresInterfaceRoute: ParametresInterfaceRoute,
  ParametresProprietesRoute: ParametresProprietesRoute,
  ParametresIndexRoute: ParametresIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
