import type { BuiltInPattern, PatternId, Token } from "./types";
import { PATTERN_IDS, isBuiltIn } from "./types";

const BANKS: Record<BuiltInPattern, string[]> = {
  sujet: [
    "palimpseste",
    "transhumance",
    "obsolescence",
    "isthme",
    "chromatophore",
    "cryoconite",
    "aporie",
    "interstice",
    "contrepoint",
    "fossile vivant",
    "dérive",
    "sédimentation",
    "éclisse",
    "phylactère",
    "anastomose",
    "résidu",
    "cartographie mentale",
    "faux-raccord",
    "écholalie",
    "marégraphe",
    "lichen",
    "phosphène",
    "strates",
    "orée",
    "dépouille d'outil",
    "héritage muet",
    "angle mort",
    "protocole oublié",
    "mesure inexacte",
    "archive humide",
    "réflexe",
    "contre-jour",
    "filigrane",
    "dette de silence",
    "habitude fossile",
    "trou de mémoire utile",
    "surface de contact",
    "seuil",
    "repli",
    "inversion",
  ],
  theme: [
    "usure",
    "attente",
    "imitation imparfaite",
    "hospitalité froide",
    "dette",
    "transmission",
    "isolement choisi",
    "vigilance",
    "oubli volontaire",
    "appartenance",
    "autorité sans visage",
    "pudeur",
    "famine d'images",
    "loyauté tordue",
    "travail invisible",
    "enfance technique",
    "domestication",
    "résistance passive",
    "mesure du temps",
    "honte utile",
    "soin excessif",
    "migration intérieure",
    "surplus de précision",
    "perte de nom",
    "rite sans dieu",
    "erreur copiée",
    "beauté accidentelle",
    "fatigue des signes",
    "réciprocité fausse",
    "patience agressive",
    "nostalgie d'un outil",
    "corps comme archive",
    "langage trop propre",
    "voisinage",
    "seuil d'intimité",
    "permission",
    "échec répété",
    "lumière trop tardive",
    "économie du secret",
    "jeu de rôles privé",
  ],
  style: [
    "brut",
    "documentaire",
    "calligraphique",
    "lithique",
    "analogique",
    "chorégraphique",
    "clinique",
    "textile",
    "palimpsestique",
    "atonal",
    "minéral",
    "laconique",
    "haptique",
    "stéréoscopique",
    "archivistique",
    "rêche",
    "sidéral",
    "sous-exposé",
    "hydrographique",
    "sèche",
    "paléographique",
    "close-up",
    "contre-plongée intérieure",
    "monochrome chaud",
    "coupe franche",
    "fondue saline",
    "rythme ralenti",
    "grain d'argent",
    "plan fixe",
    "voix off interne",
    "ellipse",
    "inventaire",
    "partition",
    "bas-relief",
    "négatif photographique",
    "cartouche",
    "staccato",
    "longue haleine",
    "détail obstiné",
    "silence monté",
  ].map((s) => s.trim()),
  nom: [
    "Calendre",
    "Vesperin",
    "Mornel",
    "Iscade",
    "Thélune",
    "Orvane",
    "Lirque",
    "Sablet",
    "Givral",
    "Esquine",
    "Dorveil",
    "Hortesse",
    "Nacreille",
    "Fremoy",
    "Istrel",
    "Javeau",
    "Cordeval",
    "Biseuil",
    "Quenel",
    "Ursal",
    "Wrenne",
    "Zelmare",
    "Albric",
    "Perchet",
    "Glaiseau",
    "Kornel",
    "Landeva",
    "Orcine",
    "Rovel",
    "Sestre",
    "Tarmoy",
    "Ulvane",
    "Varèche",
    "Ysolne",
    "Brumel",
    "Cendreille",
    "Fauvelin",
    "Grisel",
    "Hamec",
    "Nerault",
  ],
  adjectif: [
    "occlus",
    "poreux",
    "rêche",
    "atonal",
    "sidéral",
    "iodé",
    "mat",
    "oblique",
    "tardif",
    "inexact",
    "humide",
    "tranchant",
    " palier",
    "muet",
    "secondaire",
    "usagé",
    "lateral",
    "opaque",
    "mince",
    "grainé",
    "creux",
    "sédentaire",
    "volatile",
    "ancré",
    "différé",
    "sauvage domestique",
    "trop propre",
    "désaccordé",
    "lent",
    "précis à tort",
    " palimpseste",
    "sourd",
    "blanc cassé",
    "froid utile",
    "désaxé",
    "intérieur",
    "sans ombre",
    "réverbéré",
    "étroit",
    " palé",
  ].map((s) => s.trim().replace(/^palier$/, "pallier").replace(/^palé$/, "pâle")),
  sensation: [
    "picotement de sel",
    "froid de pierre",
    "goût de fer",
    "pression dans l'oreille",
    "lumière en retard",
    "odeur de cire",
    "écho ralenti",
    "peau trop lisse",
    "bruit de papier",
    "chaleur localisée",
    "vertige horizontal",
    "soif de silence",
    "mains piquées",
    "grain sous l'ongle",
    "souffle court",
    "humidité dans le tissu",
    "clignement décalé",
    "poids d'une clé",
    "vibration de vitre",
    "froid entre les dents",
    "sifflement bas",
    "goût d'iode",
    "crissement de sable",
    "chaleur d'ampoule",
    "tiraillement du cuir",
    "nausée douce",
    "engourdissement utile",
    "brûlure de corde",
    "odeur d'encre",
    "froid d'évier",
    "lumière qui cligne",
    "poussière dans la gorge",
    "battement de tempe",
    "toucher du linge rêche",
    "sel sur la lèvre",
    "silence trop net",
    "écho dans un tuyau",
    "chaleur de moteur éteint",
    "piqûre de laine",
    "goût de pluie",
  ],
  phenomene: [
    "marée interne",
    "désynchronisation",
    "halo de poussière",
    "fausse aube",
    "érosion accélérée",
    "écho préalable",
    "condensation sur le verre",
    "perte de gravité locale",
    "dérèglement d'horloge",
    "migration de moisissure",
    "ombre en retard",
    "pluie qui n'atteint pas le sol",
    "résonance d'une pièce vide",
    "glissement de meubles",
    "brouillard salin",
    "coupure de courant douce",
    "réverbération trop longue",
    "gel d'un geste",
    "dilatation d'un couloir",
    "apparition d'un seuil",
    "oubli collectif d'un mot",
    "chaleur sans source",
    "miroir qui rend trop tard",
    "sable dans les joints",
    "vent à l'intérieur",
    "double ombre",
    "ralentissement du son",
    "couleur qui quitte un objet",
    "horloge qui gagne",
    "fissure qui se referme",
    "écluse mentale",
    "marée de poussière",
    "chute de tension",
    "angle qui change",
    "nom qui glisse",
    "lumière qui reste après",
    "bruit qui arrive avant",
    "pièce plus étroite au retour",
    "reflet sans origine",
    "sédiment dans l'eau claire",
  ],
  objet: [
    "clé émoussée",
    "carnet gonflé d'humidité",
    "ampoule de rechange",
    "corde cirée",
    "verre dépoli",
    "aiguille de relieur",
    "boîte à négatifs",
    "compas faussé",
    "sceau de cire cassé",
    "loupe rayée",
    "peigne en corne",
    "bouteille d'encre",
    "poids de pendule",
    "filtre à café usé",
    "règle de tailleur",
    "bouton de nacre",
    "sachet de silice",
    "crochet de persienne",
    "thermomètre mural",
    "moule à savon",
    "lame de cutter",
    "ruban de masquage",
    "fiole d'iode",
    "tampon encreur",
    "piquet de tente",
    "verre doseur",
    "pince à linge en bois",
    "fil de fer recuit",
    "étiquette décollée",
    "sifflet plat",
    "pierre à aiguiser",
    "entonnoir étroit",
    "charnière",
    "crayon gras",
    "boîte de fusibles",
    "lentille détachée",
    "gant de jardin",
    "seau de zinc",
    "ficelle goudronnée",
    "plaque émaillée",
  ],
  lieu: [
    "souillarde",
    "débarcadère",
    "oratoire",
    "glacière",
    "cour anglaise",
    "séchoir",
    "local de compteurs",
    "cabanon de jauge",
    "salle des cartes",
    "appentis",
    "cage d'escalier secondaire",
    "galerie technique",
    "réserve de linge",
    "passe-plat",
    "belvédère fermé",
    "cale sèche",
    "salle d'attente hors service",
    "toiture inaccessible",
    "serre froide",
    "atelier de dorure",
    "guérite",
    "chambre d'ami jamais utilisée",
    "couloir en L",
    "citerne",
    "salle de triage",
    "vestiaire d'été",
    "ponton",
    "cave à sel",
    "bureau de relieur",
    "sas",
    "mezzanine trop basse",
    "coursive",
    "hangar à filets",
    "pièce sans fenêtre",
    "terrasse côté vent",
    "grenier plat",
    "lavoir",
    "salle des archives mortes",
    "niche sous l'escalier",
    "quai désaffecté",
  ],
  role: [
    "relieur",
    "doreur",
    "aiguilleur",
    "hydrographe",
    "horloger",
    "jaugeur",
    "archiviste",
    "gardien de phare",
    "tonnelier",
    "cartographe",
    "correcteur d'épreuves",
    "accordeur",
    "étalagiste",
    "ramoneur",
    "leveur de plans",
    "garde-barrière",
    " marégraphe",
    "conservateur adjoint",
    "souffleur de verre",
    "teinturier",
    "menuisier de marine",
    "standardiste",
    "huissier de salle",
    "metteur au net",
    "garçon de laboratoire",
    "veilleur",
    " relevéiste",
    "coutelier",
    "facteur d'orgues",
    "plombier de toiture",
    "gardien de cale",
    "préposé au silence",
    "inventoriste",
    "calibrateur",
    "surveillant de séchage",
    "opérateur de copie",
    "teneur de caisse",
    "guide sans public",
    "comptable de stocks morts",
    "écouteur de machines",
  ].map((s) => s.trim()),
};

export function tokensFor(pattern: BuiltInPattern): Token[] {
  return BANKS[pattern].map((word) => ({ word, pattern }));
}

export function allTokens(patterns: PatternId[]): Token[] {
  const source = patterns.filter(isBuiltIn);
  return source.flatMap(tokensFor);
}
